language: java
jdk:
  - oraclejdk8

dist: trusty

cache:
  directories:
  - $HOME/protobuf-3.6.1
  - $HOME/.m2/repository

env:
  - PATH=$PATH:$HOME/protobuf-3.6.1/bin

install:
  - bash build-helpers/install-protobuf.sh
  - mvn dependency:go-offline

script:
  - mvn -U clean install -Dgpg.skip=true -am