language: java
jdk:
  - oraclejdk8

dist: trusty

cache:
  directories:
  - $HOME/protobuf-3.6.1

install:
  - pwd
  - ls
  - bash build-helpers/install-protobuf.sh
  - mvn dependency:go-offline

script:
  - mvn clean install -Dgpg.skip=true